// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.protobuftest.protobuf;

public final class PersonProbufLiteRuntime {
  private PersonProbufLiteRuntime() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required int32 id = 2;
    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    // optional string email = 3;
    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // repeated .Person.PhoneNumber phone = 4;
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber> 
        getPhoneList();
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber getPhone(int index);
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    int getPhoneCount();
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageLite
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Person(boolean noInit) {}

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                phone_ = new java.util.ArrayList<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber>();
                mutable_bitField0_ |= 0x00000008;
              }
              phone_.add(input.readMessage(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Person.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0, 0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1, 1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2, 2),
      ;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() { return value; }

      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0: return MOBILE;
          case 1: return HOME;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.valueOf(number);
              }
            };

      private final int value;

      private PhoneType(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.PhoneType)
    }

    public interface PhoneNumberOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {

      // required string number = 1;
      /**
       * <code>required string number = 1;</code>
       */
      boolean hasNumber();
      /**
       * <code>required string number = 1;</code>
       */
      java.lang.String getNumber();
      /**
       * <code>required string number = 1;</code>
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      // optional .Person.PhoneType type = 2 [default = HOME];
      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      boolean hasType();
      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType getType();
    }
    /**
     * Protobuf type {@code Person.PhoneNumber}
     */
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessageLite
        implements PhoneNumberOrBuilder {
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private PhoneNumber(boolean noInit) {}

      private static final PhoneNumber defaultInstance;
      public static PhoneNumber getDefaultInstance() {
        return defaultInstance;
      }

      public PhoneNumber getDefaultInstanceForType() {
        return defaultInstance;
      }

      private PhoneNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                number_ = input.readBytes();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType value = com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType.valueOf(rawValue);
                if (value != null) {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<PhoneNumber> PARSER =
          new com.google.protobuf.AbstractParser<PhoneNumber>() {
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneNumber(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string number = 1;
      public static final int NUMBER_FIELD_NUMBER = 1;
      private java.lang.Object number_;
      /**
       * <code>required string number = 1;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .Person.PhoneType type = 2 [default = HOME];
      public static final int TYPE_FIELD_NUMBER = 2;
      private com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType type_;
      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
       */
      public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType getType() {
        return type_;
      }

      private void initFields() {
        number_ = "";
        type_ = com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType.HOME;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code Person.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber, Builder>
          implements com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumberOrBuilder {
        // Construct using com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          number_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType.HOME;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber getDefaultInstanceForType() {
          return com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber.getDefaultInstance();
        }

        public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber build() {
          com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber buildPartial() {
          com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber result = new com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.number_ = number_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber other) {
          if (other == com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber.getDefaultInstance()) return this;
          if (other.hasNumber()) {
            bitField0_ |= 0x00000001;
            number_ = other.number_;
            
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          return this;
        }

        public final boolean isInitialized() {
          if (!hasNumber()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string number = 1;
        private java.lang.Object number_ = "";
        /**
         * <code>required string number = 1;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string number = 1;</code>
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          number_ = getDefaultInstance().getNumber();
          
          return this;
        }
        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          number_ = value;
          
          return this;
        }

        // optional .Person.PhoneType type = 2 [default = HOME];
        private com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType type_ = com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType.HOME;
        /**
         * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
         */
        public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType getType() {
          return type_;
        }
        /**
         * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder setType(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          
          return this;
        }
        /**
         * <code>optional .Person.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneType.HOME;
          
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Person.PhoneNumber)
      }

      static {
        defaultInstance = new PhoneNumber(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Person.PhoneNumber)
    }

    public interface CountryInfoOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {

      // required string name = 1;
      /**
       * <code>required string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // required string code = 2;
      /**
       * <code>required string code = 2;</code>
       */
      boolean hasCode();
      /**
       * <code>required string code = 2;</code>
       */
      java.lang.String getCode();
      /**
       * <code>required string code = 2;</code>
       */
      com.google.protobuf.ByteString
          getCodeBytes();

      // optional int32 number = 3;
      /**
       * <code>optional int32 number = 3;</code>
       */
      boolean hasNumber();
      /**
       * <code>optional int32 number = 3;</code>
       */
      int getNumber();
    }
    /**
     * Protobuf type {@code Person.CountryInfo}
     */
    public static final class CountryInfo extends
        com.google.protobuf.GeneratedMessageLite
        implements CountryInfoOrBuilder {
      // Use CountryInfo.newBuilder() to construct.
      private CountryInfo(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private CountryInfo(boolean noInit) {}

      private static final CountryInfo defaultInstance;
      public static CountryInfo getDefaultInstance() {
        return defaultInstance;
      }

      public CountryInfo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private CountryInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                code_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                number_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<CountryInfo> PARSER =
          new com.google.protobuf.AbstractParser<CountryInfo>() {
        public CountryInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CountryInfo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<CountryInfo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string code = 2;
      public static final int CODE_FIELD_NUMBER = 2;
      private java.lang.Object code_;
      /**
       * <code>required string code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int32 number = 3;
      public static final int NUMBER_FIELD_NUMBER = 3;
      private int number_;
      /**
       * <code>optional int32 number = 3;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 number = 3;</code>
       */
      public int getNumber() {
        return number_;
      }

      private void initFields() {
        name_ = "";
        code_ = "";
        number_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getCodeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, number_);
        }
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getCodeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, number_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code Person.CountryInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo, Builder>
          implements com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfoOrBuilder {
        // Construct using com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          code_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          number_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo getDefaultInstanceForType() {
          return com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo.getDefaultInstance();
        }

        public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo build() {
          com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo buildPartial() {
          com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo result = new com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.code_ = code_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.number_ = number_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo other) {
          if (other == com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            
          }
          if (other.hasCode()) {
            bitField0_ |= 0x00000002;
            code_ = other.code_;
            
          }
          if (other.hasNumber()) {
            setNumber(other.getNumber());
          }
          return this;
        }

        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasCode()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.CountryInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          
          return this;
        }
        /**
         * <code>required string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          
          return this;
        }

        // required string code = 2;
        private java.lang.Object code_ = "";
        /**
         * <code>required string code = 2;</code>
         */
        public boolean hasCode() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string code = 2;</code>
         */
        public java.lang.String getCode() {
          java.lang.Object ref = code_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            code_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string code = 2;</code>
         */
        public com.google.protobuf.ByteString
            getCodeBytes() {
          java.lang.Object ref = code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string code = 2;</code>
         */
        public Builder setCode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          code_ = value;
          
          return this;
        }
        /**
         * <code>required string code = 2;</code>
         */
        public Builder clearCode() {
          bitField0_ = (bitField0_ & ~0x00000002);
          code_ = getDefaultInstance().getCode();
          
          return this;
        }
        /**
         * <code>required string code = 2;</code>
         */
        public Builder setCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          code_ = value;
          
          return this;
        }

        // optional int32 number = 3;
        private int number_ ;
        /**
         * <code>optional int32 number = 3;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 number = 3;</code>
         */
        public int getNumber() {
          return number_;
        }
        /**
         * <code>optional int32 number = 3;</code>
         */
        public Builder setNumber(int value) {
          bitField0_ |= 0x00000004;
          number_ = value;
          
          return this;
        }
        /**
         * <code>optional int32 number = 3;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000004);
          number_ = 0;
          
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Person.CountryInfo)
      }

      static {
        defaultInstance = new CountryInfo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Person.CountryInfo)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Person.PhoneNumber phone = 4;
    public static final int PHONE_FIELD_NUMBER = 4;
    private java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber> phone_;
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber> getPhoneList() {
      return phone_;
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public java.util.List<? extends com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumberOrBuilder> 
        getPhoneOrBuilderList() {
      return phone_;
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <code>repeated .Person.PhoneNumber phone = 4;</code>
     */
    public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumberOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      email_ = "";
      phone_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPhoneCount(); i++) {
        if (!getPhone(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(4, phone_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, phone_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.protobuftest.protobuf.PersonProbufLiteRuntime.Person, Builder>
        implements com.protobuftest.protobuf.PersonProbufLiteRuntime.PersonOrBuilder {
      // Construct using com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        phone_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person getDefaultInstanceForType() {
        return com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.getDefaultInstance();
      }

      public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person build() {
        com.protobuftest.protobuf.PersonProbufLiteRuntime.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person buildPartial() {
        com.protobuftest.protobuf.PersonProbufLiteRuntime.Person result = new com.protobuftest.protobuf.PersonProbufLiteRuntime.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.phone_ = phone_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person other) {
        if (other == com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          
        }
        if (!other.phone_.isEmpty()) {
          if (phone_.isEmpty()) {
            phone_ = other.phone_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePhoneIsMutable();
            phone_.addAll(other.phone_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getPhoneCount(); i++) {
          if (!getPhone(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuftest.protobuf.PersonProbufLiteRuntime.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuftest.protobuf.PersonProbufLiteRuntime.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        
        return this;
      }

      // required int32 id = 2;
      private int id_ ;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        
        return this;
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        
        return this;
      }

      // optional string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        
        return this;
      }

      // repeated .Person.PhoneNumber phone = 4;
      private java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber> phone_ =
        java.util.Collections.emptyList();
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = new java.util.ArrayList<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber>(phone_);
          bitField0_ |= 0x00000008;
         }
      }

      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber> getPhoneList() {
        return java.util.Collections.unmodifiableList(phone_);
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public int getPhoneCount() {
        return phone_.size();
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber getPhone(int index) {
        return phone_.get(index);
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder setPhone(
          int index, com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder setPhone(
          int index, com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber.Builder builderForValue) {
        ensurePhoneIsMutable();
        phone_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.add(value);

        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(
          int index, com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(
          com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber.Builder builderForValue) {
        ensurePhoneIsMutable();
        phone_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(
          int index, com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber.Builder builderForValue) {
        ensurePhoneIsMutable();
        phone_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder addAllPhone(
          java.lang.Iterable<? extends com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PhoneNumber> values) {
        ensurePhoneIsMutable();
        super.addAll(values, phone_);

        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder clearPhone() {
        phone_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);

        return this;
      }
      /**
       * <code>repeated .Person.PhoneNumber phone = 4;</code>
       */
      public Builder removePhone(int index) {
        ensurePhoneIsMutable();
        phone_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  public interface AddressBookOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated .Person person = 1;
    /**
     * <code>repeated .Person person = 1;</code>
     */
    java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person> 
        getPersonList();
    /**
     * <code>repeated .Person person = 1;</code>
     */
    com.protobuftest.protobuf.PersonProbufLiteRuntime.Person getPerson(int index);
    /**
     * <code>repeated .Person person = 1;</code>
     */
    int getPersonCount();
  }
  /**
   * Protobuf type {@code AddressBook}
   */
  public static final class AddressBook extends
      com.google.protobuf.GeneratedMessageLite
      implements AddressBookOrBuilder {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private AddressBook(boolean noInit) {}

    private static final AddressBook defaultInstance;
    public static AddressBook getDefaultInstance() {
      return defaultInstance;
    }

    public AddressBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private AddressBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(input.readMessage(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<AddressBook> PARSER =
        new com.google.protobuf.AbstractParser<AddressBook>() {
      public AddressBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBook> getParserForType() {
      return PARSER;
    }

    // repeated .Person person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person> person_;
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public java.util.List<? extends com.protobuftest.protobuf.PersonProbufLiteRuntime.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .Person person = 1;</code>
     */
    public com.protobuftest.protobuf.PersonProbufLiteRuntime.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook, Builder>
        implements com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBookOrBuilder {
      // Construct using com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        person_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook getDefaultInstanceForType() {
        return com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook.getDefaultInstance();
      }

      public com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook build() {
        com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook buildPartial() {
        com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook result = new com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.person_ = person_;
        return result;
      }

      public Builder mergeFrom(com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook other) {
        if (other == com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook.getDefaultInstance()) return this;
        if (!other.person_.isEmpty()) {
          if (person_.isEmpty()) {
            person_ = other.person_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePersonIsMutable();
            person_.addAll(other.person_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuftest.protobuf.PersonProbufLiteRuntime.AddressBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Person person = 1;
      private java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .Person person = 1;</code>
       */
      public java.util.List<com.protobuftest.protobuf.PersonProbufLiteRuntime.Person> getPersonList() {
        return java.util.Collections.unmodifiableList(person_);
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public int getPersonCount() {
        return person_.size();
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public com.protobuftest.protobuf.PersonProbufLiteRuntime.Person getPerson(int index) {
        return person_.get(index);
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.protobuftest.protobuf.PersonProbufLiteRuntime.Person value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonIsMutable();
        person_.set(index, value);

        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.Builder builderForValue) {
        ensurePersonIsMutable();
        person_.set(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addPerson(com.protobuftest.protobuf.PersonProbufLiteRuntime.Person value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonIsMutable();
        person_.add(value);

        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.protobuftest.protobuf.PersonProbufLiteRuntime.Person value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonIsMutable();
        person_.add(index, value);

        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addPerson(
          com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.Builder builderForValue) {
        ensurePersonIsMutable();
        person_.add(builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.protobuftest.protobuf.PersonProbufLiteRuntime.Person.Builder builderForValue) {
        ensurePersonIsMutable();
        person_.add(index, builderForValue.build());

        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends com.protobuftest.protobuf.PersonProbufLiteRuntime.Person> values) {
        ensurePersonIsMutable();
        super.addAll(values, person_);

        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder clearPerson() {
        person_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);

        return this;
      }
      /**
       * <code>repeated .Person person = 1;</code>
       */
      public Builder removePerson(int index) {
        ensurePersonIsMutable();
        person_.remove(index);

        return this;
      }

      // @@protoc_insertion_point(builder_scope:AddressBook)
    }

    static {
      defaultInstance = new AddressBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AddressBook)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
